// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateSquare(ctx context.Context, arg CreateSquareParams) error
	GetSquare(ctx context.Context, squareID int32) (GetSquareRow, error)
}

var _ Querier = (*Queries)(nil)
